// Generated by protoc-gen-swift. DO NOT EDIT.
// Source: Protos/greeting.proto
//
// To regenerate, run: scripts/proto_gen.sh

import Foundation
import SwiftProtobuf

// MARK: - Greeting V1 Messages

struct Greeting_V1_ListLanguagesResponse: Sendable, SwiftProtobuf.Message {
    static let protoMessageName = "greeting.v1.ListLanguagesResponse"
    var languages: [Greeting_V1_Language] = []

    init() {}

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeRepeatedMessageField(value: &languages)
            default: try decoder.skipField(fieldNumber: fieldNumber)
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !languages.isEmpty {
            try visitor.visitRepeatedMessageField(value: languages, fieldNumber: 1)
        }
    }
}

struct Greeting_V1_Language: Sendable, SwiftProtobuf.Message {
    static let protoMessageName = "greeting.v1.Language"
    var code: String = ""
    var name: String = ""
    var native_p: String = ""

    init() {}

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &code)
            case 2: try decoder.decodeSingularStringField(value: &name)
            case 3: try decoder.decodeSingularStringField(value: &native_p)
            default: try decoder.skipField(fieldNumber: fieldNumber)
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !code.isEmpty { try visitor.visitSingularStringField(value: code, fieldNumber: 1) }
        if !name.isEmpty { try visitor.visitSingularStringField(value: name, fieldNumber: 2) }
        if !native_p.isEmpty { try visitor.visitSingularStringField(value: native_p, fieldNumber: 3) }
    }
}

struct Greeting_V1_SayHelloRequest: Sendable, SwiftProtobuf.Message {
    static let protoMessageName = "greeting.v1.SayHelloRequest"
    var name: String = ""
    var langCode: String = ""

    init() {}

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &name)
            case 2: try decoder.decodeSingularStringField(value: &langCode)
            default: try decoder.skipField(fieldNumber: fieldNumber)
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !name.isEmpty { try visitor.visitSingularStringField(value: name, fieldNumber: 1) }
        if !langCode.isEmpty { try visitor.visitSingularStringField(value: langCode, fieldNumber: 2) }
    }
}

struct Greeting_V1_SayHelloResponse: Sendable, SwiftProtobuf.Message {
    static let protoMessageName = "greeting.v1.SayHelloResponse"
    var greeting: String = ""
    var language: String = ""
    var langCode: String = ""

    init() {}

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &greeting)
            case 2: try decoder.decodeSingularStringField(value: &language)
            case 3: try decoder.decodeSingularStringField(value: &langCode)
            default: try decoder.skipField(fieldNumber: fieldNumber)
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !greeting.isEmpty { try visitor.visitSingularStringField(value: greeting, fieldNumber: 1) }
        if !language.isEmpty { try visitor.visitSingularStringField(value: language, fieldNumber: 2) }
        if !langCode.isEmpty { try visitor.visitSingularStringField(value: langCode, fieldNumber: 3) }
    }
}

// Alias for google.protobuf.Empty used by ListLanguagesRequest.
struct Google_Protobuf_Empty: Sendable, SwiftProtobuf.Message {
    static let protoMessageName = "google.protobuf.Empty"
    init() {}
    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let _ = try decoder.nextFieldNumber() {}
    }
    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {}
}
